version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.17
        auth:
          username: "aryan3690"
          password: "ZU@tGq@1BU1"  # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t aryan-sridharala09/circleci:$TAG .
          echo $DOCKER_PASS | docker login -u aryan3690 --password ZU@tGq@1BU1
          docker push aryan-sridharala09/circleci:$TAG
workflows:
  build-workflow:
    jobs:
      - build